# you can comment some years to exclude them from the tables

source("household_income/7_household_income_statistics_provincia/13_household_income_statistics_provincia_2015.R")
source("household_income/7_household_income_statistics_provincia/12_household_income_statistics_provincia_2013.R")
source("household_income/7_household_income_statistics_provincia/11_household_income_statistics_provincia_2011.R")
source("household_income/7_household_income_statistics_provincia/10_household_income_statistics_provincia_2009.R")
source("household_income/7_household_income_statistics_provincia/9_household_income_statistics_provincia_2006.R")
source("household_income/7_household_income_statistics_provincia/8_household_income_statistics_provincia_2003.R")
source("household_income/7_household_income_statistics_provincia/7_household_income_statistics_provincia_2000.R")
source("household_income/7_household_income_statistics_provincia/6_household_income_statistics_provincia_1998.R")
source("household_income/7_household_income_statistics_provincia/5_household_income_statistics_provincia_1996.R")
source("household_income/7_household_income_statistics_provincia/4_household_income_statistics_provincia_1994.R")
source("household_income/7_household_income_statistics_provincia/3_household_income_statistics_provincia_1992.R")
source("household_income/7_household_income_statistics_provincia/2_household_income_statistics_provincia_1990.R")
