# you can comment some years to exclude them from the tables

source("household_income/household_statistics_region/household_statistics_region_2015.R")
source("household_income/household_statistics_region/household_statistics_region_2013.R")
source("household_income/household_statistics_region/household_statistics_region_2011.R")
source("household_income/household_statistics_region/household_statistics_region_2009.R")
source("household_income/household_statistics_region/household_statistics_region_2006.R")
source("household_income/household_statistics_region/household_statistics_region_2003.R")
source("household_income/household_statistics_region/household_statistics_region_2000.R")
source("household_income/household_statistics_region/household_statistics_region_1998.R")
source("household_income/household_statistics_region/household_statistics_region_1996.R")
source("household_income/household_statistics_region/household_statistics_region_1994.R")
source("household_income/household_statistics_region/household_statistics_region_1992.R")
source("household_income/household_statistics_region/household_statistics_region_1990.R")
