# you can comment some years to exclude them from the tables

source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_statistics_country/wage_by_gender_and_occupation_statistics_country_2015.R")
source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_statistics_country/wage_by_gender_and_occupation_statistics_country_2013.R")
source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_statistics_country/wage_by_gender_and_occupation_statistics_country_2011.R")
source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_statistics_country/wage_by_gender_and_occupation_statistics_country_2009.R")
source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_statistics_country/wage_by_gender_and_occupation_statistics_country_2006.R")
source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_statistics_country/wage_by_gender_and_occupation_statistics_country_2003.R")
source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_statistics_country/wage_by_gender_and_occupation_statistics_country_2000.R")
source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_statistics_country/wage_by_gender_and_occupation_statistics_country_1998.R")
source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_statistics_country/wage_by_gender_and_occupation_statistics_country_1996.R")
source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_statistics_country/wage_by_gender_and_occupation_statistics_country_1994.R")
source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_statistics_country/wage_by_gender_and_occupation_statistics_country_1992.R")
source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_statistics_country/wage_by_gender_and_occupation_statistics_country_1990.R")
