# you can comment some years to exclude them from the tables

source("wage_by_gender_and_branch_with_weights/wage_by_gender_and_branch_with_weights_statistics_comuna/wage_by_gender_and_branch_with_weights_statistics_comuna_2015.R")
source("wage_by_gender_and_branch_with_weights/wage_by_gender_and_branch_with_weights_statistics_comuna/wage_by_gender_and_branch_with_weights_statistics_comuna_2013.R")
source("wage_by_gender_and_branch_with_weights/wage_by_gender_and_branch_with_weights_statistics_comuna/wage_by_gender_and_branch_with_weights_statistics_comuna_2011.R")
