source("wage_by_gender_and_branch_with_weights/functions/load_functions.R")
#source("wage_by_gender_and_branch_with_weights/functions/batch_load_data.R") #uncomment to recalculate from 0

#source("wage_by_gender_and_branch_with_weights/process_wage_by_gender_and_branch_with_weights/process_wage_by_gender_and_branch_with_weights.R") #uncomment to recalculate from 0
source("wage_by_gender_and_branch_with_weights/processed_wage_by_gender_and_branch_with_weights/load_processed_wage_by_gender_and_branch_with_weights.R") #comment when recalculating from 0

source("wage_by_gender_and_branch_with_weights/wage_by_gender_and_branch_with_weights_tables/wage_by_gender_and_branch_with_weights_tables_country.R")
source("wage_by_gender_and_branch_with_weights/wage_by_gender_and_branch_with_weights_tables/wage_by_gender_and_branch_with_weights_tables_region.R")
source("wage_by_gender_and_branch_with_weights/wage_by_gender_and_branch_with_weights_tables/wage_by_gender_and_branch_with_weights_tables_provincia.R")
source("wage_by_gender_and_branch_with_weights/wage_by_gender_and_branch_with_weights_tables/wage_by_gender_and_branch_with_weights_tables_comuna.R")

source("wage_by_gender_and_branch_with_weights/functions/join_all.R")
