# load functions

source("wage_by_gender_with_weights/functions/batch_load.R")
source("wage_by_gender_with_weights/functions/insert_row.R")
source("wage_by_gender_with_weights/functions/move_col.R")

# load surveys (always load 2015 first!)

source("wage_by_gender_with_weights/process_wage_by_gender_with_weights/process_wage_by_gender_with_weights_2015.R")

source("wage_by_gender_with_weights/process_wage_by_gender_with_weights/process_wage_by_gender_with_weights_1990.R")
source("wage_by_gender_with_weights/process_wage_by_gender_with_weights/process_wage_by_gender_with_weights_1992.R")
source("wage_by_gender_with_weights/process_wage_by_gender_with_weights/process_wage_by_gender_with_weights_1994.R")
source("wage_by_gender_with_weights/process_wage_by_gender_with_weights/process_wage_by_gender_with_weights_1996.R")
source("wage_by_gender_with_weights/process_wage_by_gender_with_weights/process_wage_by_gender_with_weights_1998.R")

source("wage_by_gender_with_weights/process_wage_by_gender_with_weights/process_wage_by_gender_with_weights_2000.R")
source("wage_by_gender_with_weights/process_wage_by_gender_with_weights/process_wage_by_gender_with_weights_2003.R")
source("wage_by_gender_with_weights/process_wage_by_gender_with_weights/process_wage_by_gender_with_weights_2006.R")
source("wage_by_gender_with_weights/process_wage_by_gender_with_weights/process_wage_by_gender_with_weights_2009.R")

source("wage_by_gender_with_weights/process_wage_by_gender_with_weights/process_wage_by_gender_with_weights_2011.R")
source("wage_by_gender_with_weights/process_wage_by_gender_with_weights/process_wage_by_gender_with_weights_2013.R")

rm(casen_1990, casen_1992, casen_1994, casen_1996, casen_1998, 
   casen_2000, casen_2003, casen_2006, casen_2009, 
   casen_2011, casen_2013, casen_2015)
