source("household_income_with_weights/functions/libraries.R")
source("household_income_with_weights/functions/normalization.R")
source("household_income_with_weights/functions/margin_of_error.R")

source("household_income_with_weights/process_household_income_with_weights/process_household_income_with_weights.R")

source("household_income_with_weights/household_income_with_weights_tables/household_tables_with_weights_country.R")
source("household_income_with_weights/household_income_with_weights_tables/household_tables_with_weights_region.R")
source("household_income_with_weights/household_income_with_weights_tables/household_tables_with_weights_provincia.R")
source("household_income_with_weights/household_income_with_weights_tables/household_tables_with_weights_comuna.R")

source("household_income_with_weights/functions/join_all.R")
