# you can comment some years to exclude them from the tables

source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_statistics_region/wage_by_gender_and_occupation_statistics_region_2015.R")
source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_statistics_region/wage_by_gender_and_occupation_statistics_region_2013.R")
source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_statistics_region/wage_by_gender_and_occupation_statistics_region_2011.R")
source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_statistics_region/wage_by_gender_and_occupation_statistics_region_2009.R")
source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_statistics_region/wage_by_gender_and_occupation_statistics_region_2006.R")
source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_statistics_region/wage_by_gender_and_occupation_statistics_region_2003.R")
source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_statistics_region/wage_by_gender_and_occupation_statistics_region_2000.R")
source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_statistics_region/wage_by_gender_and_occupation_statistics_region_1998.R")
source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_statistics_region/wage_by_gender_and_occupation_statistics_region_1996.R")
source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_statistics_region/wage_by_gender_and_occupation_statistics_region_1994.R")
source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_statistics_region/wage_by_gender_and_occupation_statistics_region_1992.R")
source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_statistics_region/wage_by_gender_and_occupation_statistics_region_1990.R")
