# you can comment some years to exclude them from the tables

source("wage_by_gender_with_weights/wage_by_gender_with_weights_statistics_provincia/wage_by_gender_with_weights_statistics_provincia_2015.R")
source("wage_by_gender_with_weights/wage_by_gender_with_weights_statistics_provincia/wage_by_gender_with_weights_statistics_provincia_2013.R")
source("wage_by_gender_with_weights/wage_by_gender_with_weights_statistics_provincia/wage_by_gender_with_weights_statistics_provincia_2011.R")
