# you can comment some years to exclude them from the tables

source("household_income_with_weights/household_income_with_weights_statistics_provincia/household_income_with_weights_statistics_provincia_2015.R")
source("household_income_with_weights/household_income_with_weights_statistics_provincia/household_income_with_weights_statistics_provincia_2013.R")
source("household_income_with_weights/household_income_with_weights_statistics_provincia/household_income_with_weights_statistics_provincia_2011.R")
source("household_income_with_weights/household_income_with_weights_statistics_provincia/household_income_with_weights_statistics_provincia_2009.R")
source("household_income_with_weights/household_income_with_weights_statistics_provincia/household_income_with_weights_statistics_provincia_2006.R")
source("household_income_with_weights/household_income_with_weights_statistics_provincia/household_income_with_weights_statistics_provincia_2003.R")
source("household_income_with_weights/household_income_with_weights_statistics_provincia/household_income_with_weights_statistics_provincia_2000.R")
source("household_income_with_weights/household_income_with_weights_statistics_provincia/household_income_with_weights_statistics_provincia_1998.R")
source("household_income_with_weights/household_income_with_weights_statistics_provincia/household_income_with_weights_statistics_provincia_1996.R")
source("household_income_with_weights/household_income_with_weights_statistics_provincia/household_income_with_weights_statistics_provincia_1994.R")
source("household_income_with_weights/household_income_with_weights_statistics_provincia/household_income_with_weights_statistics_provincia_1992.R")
source("household_income_with_weights/household_income_with_weights_statistics_provincia/household_income_with_weights_statistics_provincia_1990.R")
