# you can comment some years to exclude them from the tables

source("household_income/6_household_income_statistics_region/13_household_income_statistics_region_2015.R")
source("household_income/6_household_income_statistics_region/12_household_income_statistics_region_2013.R")
source("household_income/6_household_income_statistics_region/11_household_income_statistics_region_2011.R")
source("household_income/6_household_income_statistics_region/10_household_income_statistics_region_2009.R")
source("household_income/6_household_income_statistics_region/9_household_income_statistics_region_2006.R")
source("household_income/6_household_income_statistics_region/8_household_income_statistics_region_2003.R")
source("household_income/6_household_income_statistics_region/7_household_income_statistics_region_2000.R")
source("household_income/6_household_income_statistics_region/6_household_income_statistics_region_1998.R")
source("household_income/6_household_income_statistics_region/5_household_income_statistics_region_1996.R")
source("household_income/6_household_income_statistics_region/4_household_income_statistics_region_1994.R")
source("household_income/6_household_income_statistics_region/3_household_income_statistics_region_1992.R")
source("household_income/6_household_income_statistics_region/2_household_income_statistics_region_1990.R")
