source("wage_by_gender_and_occupation/functions/libraries.R")
source("wage_by_gender_and_occupation/functions/normalization.R")
source("wage_by_gender_and_occupation/functions/margin_of_error.R")

source("wage_by_gender_and_occupation/process_wage_by_gender_and_occupation/process_wage_by_gender_and_occupation.R")

source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_tables/wage_by_gender_and_occupation_tables_country.R")
source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_tables/wage_by_gender_and_occupation_tables_region.R")
source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_tables/wage_by_gender_and_occupation_tables_provincia.R")
source("wage_by_gender_and_occupation/wage_by_gender_and_occupation_tables/wage_by_gender_and_occupation_tables_comuna.R")

source("wage_by_gender_and_occupation/functions/join_all.R")
