nesi_individuals_with_grants_2015$REGION <- revalue(nesi_individuals_with_grants_2015$REGION, c("Regi\u00f3n de Tarapac\u00e1" = "Tarapac\u00e1",
                                                                                                "Regi\u00f3n de Atacama" = "Atacama",
                                                                                                "Regi\u00f3n de Valpara\u00edso" = "Valpara\u00edso",
                                                                                                "Regi\u00f3n del Maule" = "Maule",
                                                                                                "Regi\u00f3n de La Araucan\u00eda" = "Araucan\u00eda",
                                                                                                "Regi\u00f3n de Ays\u00e9n del Gral. Carlos Ibá\u00f1ez del Campo" = "Ays\u00e9n",
                                                                                                "Regi\u00f3n Metropolitana" = "Metropolitana",
                                                                                                "Regi\u00f3n de Arica y Parinacota" = "Arica y Parinacota",
                                                                                                "Regi\u00f3n de Antofagasta" = "Antofagasta",
                                                                                                "Regi\u00f3n de Coquimbo" = "Coquimbo",
                                                                                                "Regi\u00f3n del Libertador Gral. Bernardo O'Higgins" = "O\u0027Higgins",
                                                                                                "Región del Biob\u00edo" = "B\u00edob\u00edo",
                                                                                                "Regi\u00f3n de Los Lagos" = "Los Lagos",
                                                                                                "Regi\u00f3n de Magallanes y Antártica Chilena" = "Magallanes",
                                                                                                "Regi\u00f3n de Los R\u00edos" = "Los R\u00edos"))

nesi_individuals_with_grants_2014$REGION <- revalue(nesi_individuals_with_grants_2014$REGION, c("Regi\u00f3n de Tarapac\u00e1" = "Tarapac\u00e1",
                                                                                                "Regi\u00f3n de Atacama" = "Atacama",
                                                                                                "Regi\u00f3n de Valpara\u00edso" = "Valpara\u00edso",
                                                                                                "Regi\u00f3n del Maule" = "Maule",
                                                                                                "Regi\u00f3n de La Araucan\u00eda" = "Araucan\u00eda",
                                                                                                "Regi\u00f3n de Ays\u00e9n del Gral. Carlos Ibá\u00f1ez del Campo" = "Ays\u00e9n",
                                                                                                "Regi\u00f3n Metropolitana" = "Metropolitana",
                                                                                                "Regi\u00f3n de Arica y Parinacota" = "Arica y Parinacota",
                                                                                                "Regi\u00f3n de Antofagasta" = "Antofagasta",
                                                                                                "Regi\u00f3n de Coquimbo" = "Coquimbo",
                                                                                                "Regi\u00f3n del Libertador Gral. Bernardo O'Higgins" = "O\u0027Higgins",
                                                                                                "Región del Biob\u00edo" = "B\u00edob\u00edo",
                                                                                                "Regi\u00f3n de Los Lagos" = "Los Lagos",
                                                                                                "Regi\u00f3n de Magallanes y Antártica Chilena" = "Magallanes",
                                                                                                "Regi\u00f3n de Los R\u00edos" = "Los R\u00edos"))

nesi_individuals_with_grants_2013$REGION <- revalue(nesi_individuals_with_grants_2013$REGION, c("Regi\u00f3n de Tarapac\u00e1" = "Tarapac\u00e1",
                                                                                                "Regi\u00f3n de Atacama" = "Atacama",
                                                                                                "Regi\u00f3n de Valpara\u00edso" = "Valpara\u00edso",
                                                                                                "Regi\u00f3n del Maule" = "Maule",
                                                                                                "Regi\u00f3n de La Araucan\u00eda" = "Araucan\u00eda",
                                                                                                "Regi\u00f3n de Ays\u00e9n del Gral. Carlos Ibá\u00f1ez del Campo" = "Ays\u00e9n",
                                                                                                "Regi\u00f3n Metropolitana" = "Metropolitana",
                                                                                                "Regi\u00f3n de Arica y Parinacota" = "Arica y Parinacota",
                                                                                                "Regi\u00f3n de Antofagasta" = "Antofagasta",
                                                                                                "Regi\u00f3n de Coquimbo" = "Coquimbo",
                                                                                                "Regi\u00f3n del Libertador Gral. Bernardo O'Higgins" = "O\u0027Higgins",
                                                                                                "Región del Biob\u00edo" = "B\u00edob\u00edo",
                                                                                                "Regi\u00f3n de Los Lagos" = "Los Lagos",
                                                                                                "Regi\u00f3n de Magallanes y Antártica Chilena" = "Magallanes",
                                                                                                "Regi\u00f3n de Los R\u00edos" = "Los R\u00edos"))

nesi_individuals_with_grants_2012$REGION <- revalue(nesi_individuals_with_grants_2012$REGION, c("Regi\u00f3n de Tarapac\u00e1" = "Tarapac\u00e1",
                                                                                                "Regi\u00f3n de Atacama" = "Atacama",
                                                                                                "Regi\u00f3n de Valpara\u00edso" = "Valpara\u00edso",
                                                                                                "Regi\u00f3n del Maule" = "Maule",
                                                                                                "Regi\u00f3n de La Araucan\u00eda" = "Araucan\u00eda",
                                                                                                "Regi\u00f3n de Ays\u00e9n del Gral. Carlos Iba\u00f1ez del Campo" = "Ays\u00e9n",
                                                                                                "Regi\u00f3n Metropolitana" = "Metropolitana",
                                                                                                "Regi\u00f3n de Arica y Parinacota" = "Arica y Parinacota",
                                                                                                "Regi\u00f3n de Antofagasta" = "Antofagasta",
                                                                                                "Regi\u00f3n de Coquimbo" = "Coquimbo",
                                                                                                "Regi\u00f3n del Libertador Gral. Bernardo O'Higgins" = "O\u0027Higgins",
                                                                                                "Región del Biob\u00edo" = "B\u00edob\u00edo",
                                                                                                "Regi\u00f3n de Los Lagos" = "Los Lagos",
                                                                                                "Regi\u00f3n de Magallanes y Antártica Chilena" = "Magallanes",
                                                                                                "Regi\u00f3n de Los R\u00edos" = "Los R\u00edos"))

nesi_individuals_with_grants_2011$REGION <- revalue(nesi_individuals_with_grants_2011$REGION, c("Regi\u00f3n de Tarapac\u00e1" = "Tarapac\u00e1",
                                                                                                "Regi\u00f3n de Atacama" = "Atacama",
                                                                                                "Regi\u00f3n de Valparaiso" = "Valpara\u00edso",
                                                                                                "Regi\u00f3n del Maule" = "Maule",
                                                                                                "Regi\u00f3n de La Araucan\u00eda" = "Araucan\u00eda",
                                                                                                "Regi\u00f3n De Ais\u00e9n del Gral. Carlos Iba\u00f1ez del Campo" = "Ays\u00e9n",
                                                                                                "Regi\u00f3n Metropolitana" = "Metropolitana",
                                                                                                "Regi\u00f3n de Arica y Parinacota" = "Arica y Parinacota",
                                                                                                "Regi\u00f3n de Antofagasta" = "Antofagasta",
                                                                                                "Regi\u00f3n de Coquimbo" = "Coquimbo",
                                                                                                "Regi\u00f3n del Libertador Gral Bernardo O'higgins" = "O\u0027Higgins",
                                                                                                "Región del Bio B\u00edo" = "B\u00edob\u00edo",
                                                                                                "Regi\u00f3n de los Lagos" = "Los Lagos",
                                                                                                "Regi\u00f3n de Magallanes y Antártica Chilena" = "Magallanes",
                                                                                                "Regi\u00f3n de los R\u00edos" = "Los R\u00edos"))

nesi_individuals_with_grants_2010$REGION <- revalue(nesi_individuals_with_grants_2010$REGION, c("Regi\u00f3n de Tarapac\u00e1" = "Tarapac\u00e1",
                                                                                                "Regi\u00f3n de Atacama" = "Atacama",
                                                                                                "Regi\u00f3n de Valparaiso" = "Valpara\u00edso",
                                                                                                "Regi\u00f3n del Maule" = "Maule",
                                                                                                "Regi\u00f3n de La Araucan\u00eda" = "Araucan\u00eda",
                                                                                                "Regi\u00f3n De Ais\u00e9n del Gral. Carlos Iba\u00f1ez del Campo" = "Ays\u00e9n",
                                                                                                "Regi\u00f3n Metropolitana" = "Metropolitana",
                                                                                                "Regi\u00f3n de Arica y Parinacota" = "Arica y Parinacota",
                                                                                                "Regi\u00f3n de Antofagasta" = "Antofagasta",
                                                                                                "Regi\u00f3n de Coquimbo" = "Coquimbo",
                                                                                                "Regi\u00f3n del Libertador Gral Bernardo O'higgins" = "O\u0027Higgins",
                                                                                                "Región del Bio B\u00edo" = "B\u00edob\u00edo",
                                                                                                "Regi\u00f3n de los Lagos" = "Los Lagos",
                                                                                                "Regi\u00f3n de Magallanes y Antártica Chilena" = "Magallanes",
                                                                                                "Regi\u00f3n de los R\u00edos" = "Los R\u00edos"))






