# you can comment some years to exclude them from the tables

source("wage_by_gender_and_occupation_with_weights/wage_by_gender_and_occupation_with_weights_statistics_region/wage_by_gender_and_occupation_with_weights_statistics_region_2015.R")
source("wage_by_gender_and_occupation_with_weights/wage_by_gender_and_occupation_with_weights_statistics_region/wage_by_gender_and_occupation_with_weights_statistics_region_2013.R")
source("wage_by_gender_and_occupation_with_weights/wage_by_gender_and_occupation_with_weights_statistics_region/wage_by_gender_and_occupation_with_weights_statistics_region_2011.R")
