# you can comment some years to exclude them from the tables

source("household_income/8_household_income_statistics_comuna/13_household_income_statistics_comuna_2015.R")
source("household_income/8_household_income_statistics_comuna/12_household_income_statistics_comuna_2013.R")
source("household_income/8_household_income_statistics_comuna/11_household_income_statistics_comuna_2011.R")
source("household_income/8_household_income_statistics_comuna/10_household_income_statistics_comuna_2009.R")
source("household_income/8_household_income_statistics_comuna/9_household_income_statistics_comuna_2006.R")
source("household_income/8_household_income_statistics_comuna/8_household_income_statistics_comuna_2003.R")
source("household_income/8_household_income_statistics_comuna/7_household_income_statistics_comuna_2000.R")
source("household_income/8_household_income_statistics_comuna/6_household_income_statistics_comuna_1998.R")
source("household_income/8_household_income_statistics_comuna/5_household_income_statistics_comuna_1996.R")
source("household_income/8_household_income_statistics_comuna/4_household_income_statistics_comuna_1994.R")
source("household_income/8_household_income_statistics_comuna/3_household_income_statistics_comuna_1992.R")
source("household_income/8_household_income_statistics_comuna/2_household_income_statistics_comuna_1990.R")
