# load surveys (always load 2015 first!)

source("wage_by_gender_and_branch_with_weights/process_wage_by_gender_and_branch_with_weights/process_wage_by_gender_and_branch_with_weights_2015.R")

source("wage_by_gender_and_branch_with_weights/process_wage_by_gender_and_branch_with_weights/process_wage_by_gender_and_branch_with_weights_2011.R")
source("wage_by_gender_and_branch_with_weights/process_wage_by_gender_and_branch_with_weights/process_wage_by_gender_and_branch_with_weights_2013.R")

rm(casen_2011, casen_2013, casen_2015)

save(wage_by_gender_and_branch_with_weights_2011, file = paste0(getwd(),"/wage_by_gender_and_branch_with_weights/processed_wage_by_gender_and_branch_with_weights/wage_by_gender_and_branch_with_weights_2011.RData"))
save(wage_by_gender_and_branch_with_weights_2013, file = paste0(getwd(),"/wage_by_gender_and_branch_with_weights/processed_wage_by_gender_and_branch_with_weights/wage_by_gender_and_branch_with_weights_2013.RData"))
save(wage_by_gender_and_branch_with_weights_2015, file = paste0(getwd(),"/wage_by_gender_and_branch_with_weights/processed_wage_by_gender_and_branch_with_weights/wage_by_gender_and_branch_with_weights_2015.RData"))
