# you can comment some years to exclude them from the tables

source("wage_by_gender_and_branch_with_weights/wage_by_gender_and_branch_with_weights_statistics_country/wage_by_gender_and_branch_with_weights_statistics_country_2015.R")
source("wage_by_gender_and_branch_with_weights/wage_by_gender_and_branch_with_weights_statistics_country/wage_by_gender_and_branch_with_weights_statistics_country_2013.R")
source("wage_by_gender_and_branch_with_weights/wage_by_gender_and_branch_with_weights_statistics_country/wage_by_gender_and_branch_with_weights_statistics_country_2011.R")
